# Generated by Django 4.1.1 on 2022-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_project_name_space_alter_project_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yaml',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Yaml File Path'),
        ),
    ]
