# Generated by Django 4.1.1 on 2022-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='Username')),
                ('email', models.CharField(max_length=32, verbose_name='E-mail')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('mobile_phone', models.CharField(max_length=12, verbose_name='Mobilphone')),
            ],
        ),
    ]
